---
- name: Download fabio binary
  get_url:
    url: "{{ fabio_binary_url }}"
    dest: /usr/local/bin/fabio
    owner: root
    group: root
    mode: 0755

- name: Create fabio user
  user:
    name: fabio

- name: Deploy fabio systemd service
  copy:
    src: fabio.service
    dest: /etc/systemd/system/fabio.service
  notify:
    - reload systemd daemons
    - restart fabio

- name: Create fabio folder
  file:
    path: /etc/fabio
    state: directory
    owner: root
    group: fabio
    mode: 0750
  notify: restart fabio

- name: Create fabio.properties file
  template:
    src: fabio.properties.j2
    dest: /etc/fabio/fabio.properties
    mode: 0640
    owner: root
    group: fabio
  notify: restart fabio

- name: Generate certificate folder
  file:
    state: directory
    path: /etc/ssl/fabio/
    owner: root
    group: fabio
    mode: 0750

- name: Install pip3 and python libs dependencies
  apt:
    name:
      - python3-pip
      - python3-openssl
      - python3-passlib
    state: present

- name: Generate dummy certificate
  block:
  - name: Generate an OpenSSL private key.
    openssl_privatekey:
      path: /etc/ssl/fabio/dummy-key.pem
      owner: root
      group: fabio
      mode: 0640

  - name: Generate an OpenSSL CSR.
    openssl_csr:
      path: /etc/ssl/fabio/dummy.csr
      privatekey_path: /etc/ssl/fabio/dummy-key.pem
      common_name: "local.shaka.xyz"
      owner: root
      group: fabio
      mode: 0640

  - name: Generate a Self Signed OpenSSL certificate.
    openssl_certificate:
      path: /etc/ssl/fabio/dummy-cert.pem
      privatekey_path: /etc/ssl/fabio/dummy-key.pem
      csr_path: /etc/ssl/fabio/dummy.csr
      provider: selfsigned
      owner: root
      group: fabio
      mode: 0640

- name: Create admin htpasswd file
  community.general.htpasswd:
    path: /etc/fabio/admin.creds
    name: admin
    password: "{{ fabio_admin_password }}"
    owner: root
    group: fabio
    mode: 0640

- name: Ensure fabiolb is started
  service:
    name: fabio
    state: started
    enabled: true
